package View;

public class HomeAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HomeAdmin.class.getName());
    private final model.Akun adminLogin;
    
    public HomeAdmin(model.Akun adminLogin) {
        this.adminLogin = adminLogin;
        initComponents();
        this.setLocationRelativeTo(null);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonKelolaPelatihan = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonVerifikasiPengajuan = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButtonVerifikasiSertifikat = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButtonLihatInsentif = new javax.swing.JButton();
        jButtonLogOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Screenshot 2025-10-29 220303.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 100, -1));

        jLabel3.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jLabel3.setText("Kelola Pelatihan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, 100, -1));

        jButtonKelolaPelatihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKelolaPelatihanActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonKelolaPelatihan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 140, 150));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Screenshot 2025-10-29 220313.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 100, 90));

        jLabel5.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jLabel5.setText("Verifikasi Pengajuan");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 530, -1, -1));

        jButtonVerifikasiPengajuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerifikasiPengajuanActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVerifikasiPengajuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 140, 150));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Screenshot 2025-10-29 220323.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jLabel7.setText("Verifikasi Sertifikat");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 530, -1, -1));

        jButtonVerifikasiSertifikat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerifikasiSertifikatActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVerifikasiSertifikat, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 140, 150));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Screenshot 2025-10-29 220328.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 430, 100, -1));

        jLabel9.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jLabel9.setText("Daftar Insentif");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 530, 90, 20));

        jButtonLihatInsentif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLihatInsentifActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLihatInsentif, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, 140, 150));

        jButtonLogOut.setBackground(new java.awt.Color(204, 204, 204));
        jButtonLogOut.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jButtonLogOut.setText("Log Out");
        jButtonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogOutActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/HOMEADMIN.gif"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonKelolaPelatihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKelolaPelatihanActionPerformed
        this.dispose();
        new KelolaPelatihan(adminLogin).setVisible(true);
    }//GEN-LAST:event_jButtonKelolaPelatihanActionPerformed

    private void jButtonVerifikasiSertifikatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerifikasiSertifikatActionPerformed
        this.dispose();
        new VerifikasiSertifikat(adminLogin).setVisible(true);
    }//GEN-LAST:event_jButtonVerifikasiSertifikatActionPerformed

    private void jButtonLihatInsentifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLihatInsentifActionPerformed
        this.dispose();
        new LihatInsentif(adminLogin).setVisible(true);
    }//GEN-LAST:event_jButtonLihatInsentifActionPerformed

    private void jButtonVerifikasiPengajuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerifikasiPengajuanActionPerformed
        this.dispose();
        new VerifikasiPengajuan(adminLogin).setVisible(true);
    }//GEN-LAST:event_jButtonVerifikasiPengajuanActionPerformed

    private void jButtonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogOutActionPerformed
        this.dispose();
        new HOMEE().setVisible(true);
    }//GEN-LAST:event_jButtonLogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HomeAdmin(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonKelolaPelatihan;
    private javax.swing.JButton jButtonLihatInsentif;
    private javax.swing.JButton jButtonLogOut;
    private javax.swing.JButton jButtonVerifikasiPengajuan;
    private javax.swing.JButton jButtonVerifikasiSertifikat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
