package View;

import javax.swing.JOptionPane;
import model.Akun;
import service.AuthService;

public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());
    private final AuthService authService = new AuthService();

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButtonMasuk = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButtonRegis = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 280, 40));

        jButtonMasuk.setBackground(new java.awt.Color(255, 204, 0));
        jButtonMasuk.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jButtonMasuk.setText("OK");
        jButtonMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMasukActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 90, 30));

        jPasswordField1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 280, 40));

        jButtonRegis.setBackground(new java.awt.Color(204, 204, 204));
        jButtonRegis.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jButtonRegis.setText("Belum punya akun? Registrasi disini!");
        jButtonRegis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegis, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, -1, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Login.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisActionPerformed
        this.dispose();
        new RegistrasiAkun().setVisible(true);
    }//GEN-LAST:event_jButtonRegisActionPerformed

    private void jButtonMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMasukActionPerformed
        String email = jTextField1.getText().trim();
        String password = new String(jPasswordField1.getPassword());

        if (email.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Email dan password wajib diisi.", 
                    "Validasi", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            Akun akun = authService.login(email, password);

            if (akun == null) {
                JOptionPane.showMessageDialog(this, "Email atau Password salah!", 
                        "Login Gagal", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (akun.getPeran() != null) {
                if ("admin".equalsIgnoreCase(akun.getPeran())) {
                    JOptionPane.showMessageDialog(this, 
                            "Halo Admin " + akun.getNama() + " 👑",
                            "Selamat Datang", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, 
                            "Hai " + akun.getNama() + ", selamat datang di Fincare! 🌼",
                            "Selamat Datang", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            
            if ("admin".equalsIgnoreCase(akun.getPeran())) {
                new View.HomeAdmin(akun).setVisible(true);
            } else {
                new View.HomePengguna(akun).setVisible(true);
            }

            this.dispose();

        } catch (Exception e) {
            logger.log(java.util.logging.Level.SEVERE, "Login error", e);
            JOptionPane.showMessageDialog(this, 
                    "Terjadi kesalahan: " + e.getMessage(), 
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonMasukActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMasuk;
    private javax.swing.JButton jButtonRegis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
