package View;

import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;

public class VerifikasiPengajuan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VerifikasiPengajuan.class.getName());
    private final service.PengajuanService pengajuanSvc = new service.PengajuanService();
    private javax.swing.table.DefaultTableModel model;
    private Integer selectedId = null;
    private final model.Akun adminLogin;
    private final Integer adminNik;
    
    /**
     * Creates new form Verifikasi_Pengajuan
     */
    public VerifikasiPengajuan(model.Akun adminLogin) {
        this.adminLogin = adminLogin;
        this.adminNik = adminLogin.getNik();
        initComponents();
        this.setLocationRelativeTo(null);
        initTable();        
        HubungPencarianLangsung();  
        muatData(null);       

        jButtonDiterima.addActionListener(e -> ubahStatus("DITERIMA")); 
        jButtonDitolak.addActionListener(e -> ubahStatus("DITOLAK")); 
        jButton2.addActionListener(e -> {
          this.dispose();
          new HomeAdmin(adminLogin).setVisible(true);
        });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextFieldPencarian = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonDitolak = new javax.swing.JButton();
        jButtonDiterima = new javax.swing.JButton();
        jTextFieldNama = new javax.swing.JTextField();
        jTextFieldAlasan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldPencarian.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextFieldPencarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPencarianActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPencarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 250, 30));

        jButton2.setBackground(new java.awt.Color(255, 204, 0));
        jButton2.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jButton2.setText("Kembali");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 610, 200));

        jButtonDitolak.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jButtonDitolak.setForeground(new java.awt.Color(255, 0, 0));
        jButtonDitolak.setText("Ditolak");
        jButtonDitolak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDitolakActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDitolak, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 80, -1));

        jButtonDiterima.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jButtonDiterima.setForeground(new java.awt.Color(51, 255, 51));
        jButtonDiterima.setText("Diterima");
        jButtonDiterima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDiterimaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDiterima, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, -1, -1));

        jTextFieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNamaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 330, 30));
        getContentPane().add(jTextFieldAlasan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 330, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Verifikasi Pengajuan.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        new HomeAdmin(adminLogin).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextFieldPencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPencarianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPencarianActionPerformed

    private void jTextFieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNamaActionPerformed

    private void jButtonDiterimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDiterimaActionPerformed
        if (selectedId == null) {
            return;
        }
        try {
            pengajuanSvc.setStatus(selectedId, "DITERIMA",
                adminLogin == null ? null : adminLogin.getNik());
            muatData(jTextFieldPencarian.getText().trim());
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_jButtonDiterimaActionPerformed

    private void jButtonDitolakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDitolakActionPerformed
        if (selectedId == null) {
            return;
        }
        try {
            pengajuanSvc.setStatus(selectedId, "DITOLAK",
                adminLogin == null ? null : adminLogin.getNik());
            muatData(jTextFieldPencarian.getText().trim());
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_jButtonDitolakActionPerformed
    
    private void initTable() {
        model = new javax.swing.table.DefaultTableModel(
            new Object[]{"ID", "NIK", "Nama", "Pekerjaan", "Penghasilan", "Bidang", "Tanggal", "Status"}, 0) {
            @Override 
            public boolean isCellEditable(int r, int c) {
                return false; 
            }
        };
        jTable1.setModel(model);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) isiDetailDariTabel();
        });
    }

    private void muatData(String q) {
        var df = (java.text.DecimalFormat)
                java.text.NumberFormat.getCurrencyInstance(new java.util.Locale("id","ID"));
        df.setMaximumFractionDigits(0);
        
        try {
            model.setRowCount(0);
            var rows = pengajuanSvc.cariDenganAkun(q);
            for (var r : rows) {
                model.addRow(new Object[]{
                    r.idPengajuan,
                    r.nikPengguna,
                    r.nama,
                    r.pekerjaan,
                    df.format(r.penghasilan),
                    r.bidangDiminati,
                    (r.tanggalPengajuan == null ? "" : r.tanggalPengajuan.toString()),
                    r.statusPengajuan
                });
            }
            selectedId = null;
            jTextFieldNama.setText("");
            jTextFieldAlasan.setText("");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Gagal memuat: " + ex.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void isiDetailDariTabel() {
        int r = jTable1.getSelectedRow();
        if (r < 0) { selectedId = null; return; }
        selectedId = (Integer) model.getValueAt(r, 0);

        var id = selectedId;
        var rows = pengajuanSvc.cariDenganAkun(null);
        Model.PengajuanBaris row = rows.stream().filter(x -> x.idPengajuan.equals(id)).findFirst().orElse(null);
        if (row != null) {
            jTextFieldNama.setText(row.nama);
            jTextFieldAlasan.setText(row.alasanPengajuan);
        }
    }

    private void PencarianLangsung() {
        String q = jTextFieldPencarian.getText().trim();
        muatData(q.isEmpty() ? null : q);
    }

    private void HubungPencarianLangsung() {
        jTextFieldPencarian.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override 
            public void insertUpdate(DocumentEvent e) {
                PencarianLangsung(); 
            }
            @Override 
            public void removeUpdate(DocumentEvent e) {
                PencarianLangsung();
            }
            @Override 
            public void changedUpdate(DocumentEvent e) {
                PencarianLangsung(); 
            }
        });
    }
    
    private void ubahStatus(String statusBaru) {
        if (selectedId == null) {
          JOptionPane.showMessageDialog(this, "Pilih baris pengajuan dulu.");
          return;
        }
        if (adminNik == null) {
          JOptionPane.showMessageDialog(this, "Sesi admin hilang. Silakan login ulang.");
          return;
        }
        try {
          pengajuanSvc.ubahStatus(selectedId, statusBaru, adminNik);
          JOptionPane.showMessageDialog(this, "Status diubah ke " + statusBaru + ".");
          muatData(jTextFieldPencarian.getText().trim());
        } catch (Exception ex) {
          JOptionPane.showMessageDialog(this, "Gagal memperbarui: " + ex.getMessage(),
              "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonDiterima;
    private javax.swing.JButton jButtonDitolak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldAlasan;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTextField jTextFieldPencarian;
    // End of variables declaration//GEN-END:variables
}
