package View;

import java.time.LocalDate;
import javax.swing.table.DefaultTableModel;
import model.Akun;
import service.PengajuanService;

public class AjukanBantuan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AjukanBantuan.class.getName());
    private final PengajuanService pengajuanSvc = new PengajuanService();
    private final Akun penggunaLogin;
    private DefaultTableModel tblModel;
    private Integer selectedId = null;
    
    /**
     * Creates new form Ajukan_Bantuan
     */
    public AjukanBantuan(model.Akun penggunaLogin) {
        if (penggunaLogin == null) {
            throw new IllegalArgumentException("penggunaLogin null – pastikan dipass dari Login/HomePengguna");
        }
        this.penggunaLogin = penggunaLogin;;
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        initTable();
        jTextFieldTanggal.setText(LocalDate.now().toString());

        jTablePengajuan.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && jTablePengajuan.getSelectedRow() != -1) {
                int row = jTablePengajuan.getSelectedRow();

                String bidang  = jTablePengajuan.getValueAt(row, 1).toString();
                String alasan  = jTablePengajuan.getValueAt(row, 2).toString();
                String tanggal = jTablePengajuan.getValueAt(row, 3).toString();

                jTextFieldBidang.setText(bidang);
                jTextFieldAlasan.setText(alasan);
                jTextFieldTanggal.setText(tanggal);
            }
        });

        muatData();

        if (jTablePengajuan.getRowCount() > 0) {
            jTablePengajuan.setRowSelectionInterval(0, 0);
        }    

        if (jTablePengajuan.getRowCount() > 0) {
            int row = jTablePengajuan.getSelectedRow();
            jTextFieldBidang.setText(jTablePengajuan.getValueAt(row, 1).toString());
            jTextFieldAlasan.setText(jTablePengajuan.getValueAt(row, 2).toString());
            String tanggal = jTablePengajuan.getValueAt(row, 3).toString();
            if (tanggal.length() >= 10) tanggal = tanggal.substring(0,10);
            jTextFieldTanggal.setText(tanggal);
        }
        
        refreshTombol();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonKembali = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePengajuan = new javax.swing.JTable();
        jTextFieldBidang = new javax.swing.JTextField();
        jTextFieldAlasan = new javax.swing.JTextField();
        jTextFieldTanggal = new javax.swing.JTextField();
        jButtonOK = new javax.swing.JButton();
        jButtonBatalkan = new javax.swing.JButton();
        jButtonRefresh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonKembali.setBackground(new java.awt.Color(255, 204, 0));
        jButtonKembali.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonKembali.setText("Kembali");
        jButtonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 490, 110, 40));

        jTablePengajuan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablePengajuan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 710, 180));

        jTextFieldBidang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBidangActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldBidang, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 300, -1));

        jTextFieldAlasan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAlasanActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldAlasan, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 300, -1));

        jTextFieldTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTanggalActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 300, -1));

        jButtonOK.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, 90, 30));

        jButtonBatalkan.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jButtonBatalkan.setForeground(new java.awt.Color(255, 0, 51));
        jButtonBatalkan.setText("Batalkan Pengajuan");
        jButtonBatalkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBatalkanActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBatalkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 440, 150, 30));

        jButtonRefresh.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jButtonRefresh.setText("Refresh");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 90, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Ajukan Bantuan_1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKembaliActionPerformed
        this.dispose();
        new HomePengguna(penggunaLogin).setVisible(true);
    }//GEN-LAST:event_jButtonKembaliActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        simpanPengajuan();
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jTextFieldBidangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBidangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBidangActionPerformed

    private void jTextFieldAlasanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAlasanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAlasanActionPerformed

    private void jTextFieldTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTanggalActionPerformed

    private void jButtonBatalkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBatalkanActionPerformed
        if (pendingId == null) 
            return;

        pengajuanSvc.batalkanPengajuan(pendingId, penggunaLogin.getNik());

        muatData();
        refreshTombol();
    }//GEN-LAST:event_jButtonBatalkanActionPerformed

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        muatData();
        refreshTombol();
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    private void initTable() {
        tblModel = new javax.swing.table.DefaultTableModel(
            new Object[]{"ID", "Bidang", "Alasan", "Tanggal", "Status"}, 0
        ) {
            @Override 
            public boolean isCellEditable(int r, int c) { 
                return false; 
            }
        };
        jTablePengajuan.setModel(tblModel);
    }

    private void simpanPengajuan() {
        try {
            if (pengajuanSvc.hasPendingByNik(penggunaLogin.getNik())) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Masih ada pengajuan MENUNGGU. Batalkan dulu.");
                return;
            }
            var pb = new model.PengajuanBantuan();
            pb.setPengguna(penggunaLogin);
            pb.setBidangDiminati(jTextFieldBidang.getText().trim());
            pb.setAlasanPengajuan(jTextFieldAlasan.getText().trim());
            pb.setStatusPengajuan("MENUNGGU");
            pb.setTanggalPengajuan(java.time.LocalDateTime.now());

            pengajuanSvc.tambah(pb);
            javax.swing.JOptionPane.showMessageDialog(this, "Pengajuan dikirim.");
            muatData();
            refreshTombol();
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private Integer pendingId;

    private void muatData() {
        tblModel.setRowCount(0);
        pendingId = null;

        var list = pengajuanSvc.temukanSemua();
        for (var x : list) {
            if (x.getPengguna() == null) 
                continue;
            if (!x.getPengguna().getNik().equals(penggunaLogin.getNik())) 
                continue;

            String tgl = x.getTanggalPengajuan() == null ? "-" : x.getTanggalPengajuan().toString();
            tblModel.addRow(new Object[]{
                x.getIdPengajuan(),
                x.getBidangDiminati(),
                x.getAlasanPengajuan(),
                tgl,
                x.getStatusPengajuan()
            });

            if ("MENUNGGU".equalsIgnoreCase(x.getStatusPengajuan())) {
                pendingId = x.getIdPengajuan();
            }
        }

        if (jTablePengajuan.getRowCount() > 0) {
            jTablePengajuan.setRowSelectionInterval(0, 0);
        } else {
            jTextFieldBidang.setText("");
            jTextFieldAlasan.setText("");
            jTextFieldTanggal.setText(LocalDate.now().toString());
            selectedId = null;
        }
    }

    private void refreshTombol() {
        boolean adaPending = pengajuanSvc.hasPendingByNik(penggunaLogin.getNik());
        jButtonOK.setEnabled(!adaPending);
        jButtonBatalkan.setEnabled(adaPending);
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBatalkan;
    private javax.swing.JButton jButtonKembali;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePengajuan;
    private javax.swing.JTextField jTextFieldAlasan;
    private javax.swing.JTextField jTextFieldBidang;
    private javax.swing.JTextField jTextFieldTanggal;
    // End of variables declaration//GEN-END:variables

}
