package View;

import javax.swing.JOptionPane;
//import javax.swing.SwingUtilities;

public class HomePengguna extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HomePengguna.class.getName());
    private final model.Akun penggunaLogin;
//    private GifPlayer player;

    public HomePengguna(model.Akun penggunaLogin) {
        this.penggunaLogin = penggunaLogin;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);

        if (this.penggunaLogin == null) {
            JOptionPane.showMessageDialog(this,
                "Sesi belum ada. Silakan login dulu ya 🙂");
            this.dispose();
            new Login().setVisible(true);
            return;
        }
        
//        SwingUtilities.invokeLater(() -> {
//            // gunakan PATH yang sama persis dengan file kamu
//            final String PATH = "/Image/HOMEPENGGUNA2.gif";
//
//            // cek resource sekali
//            var url = HomePengguna.class.getResource(PATH);
//            System.out.println("GIF URL = " + url);
//
//            if (url != null) {
//                // fallback: tampilkan dulu agar langsung kelihatan
//                jLabelHome.setIcon(new javax.swing.ImageIcon(url));
//            }
//
//            // jalankan GifPlayer (lebih halus)
//            player = new GifPlayer(jLabelHome);
//            player.loadFromResource(PATH, jLabelHome.getWidth(), jLabelHome.getHeight());
//            player.start();
//
//            // jadikan jLabelHome benar-benar background (di paling belakang)
//            getContentPane().setComponentZOrder(jLabelHome, getContentPane().getComponentCount() - 1);
//            jLabelHome.revalidate();
//            jLabelHome.repaint();
//        });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonAjukanBantuan = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButtonPilihPelatihan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButtonUploadSertifikat = new javax.swing.JButton();
        jButtonProfilPengguna = new javax.swing.JButton();
        jButtonLihatInsentif = new javax.swing.JButton();
        jButtonLogOut = new javax.swing.JButton();
        jLabelHome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Screenshot 2025-10-29 220328.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 430, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jLabel4.setText("Pilih Pelatihan");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 540, 80, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Screenshot 2025-10-29 232341.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jLabel6.setText("Ajukan Bantuan");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 540, -1, -1));

        jButtonAjukanBantuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjukanBantuanActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAjukanBantuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 140, 150));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Cuplikan layar 2025-11-02 120808.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 120, 110));

        jButtonPilihPelatihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPilihPelatihanActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPilihPelatihan, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 140, 150));

        jLabel2.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jLabel2.setText("Upload Sertifikat");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jLabel9.setText("Lihat Insentif");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 540, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Cuplikan layar 2025-11-02 120553.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 100, 110));

        jButtonUploadSertifikat.setToolTipText("");
        jButtonUploadSertifikat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUploadSertifikatActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonUploadSertifikat, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 140, 150));

        jButtonProfilPengguna.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jButtonProfilPengguna.setText("Profil Saya");
        jButtonProfilPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProfilPenggunaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonProfilPengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, 30));

        jButtonLihatInsentif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLihatInsentifActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLihatInsentif, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, 140, 150));

        jButtonLogOut.setBackground(new java.awt.Color(204, 204, 204));
        jButtonLogOut.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jButtonLogOut.setText("Log Out");
        jButtonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogOutActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 80, 30));

        jLabelHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/HOMEPENGGUNA2.gif"))); // NOI18N
        getContentPane().add(jLabelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUploadSertifikatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUploadSertifikatActionPerformed
        this.dispose();
        new Sertifikat_dan_DataDiri(penggunaLogin).setVisible(true);
    }//GEN-LAST:event_jButtonUploadSertifikatActionPerformed

    private void jButtonPilihPelatihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPilihPelatihanActionPerformed
        this.dispose();
        new PilihanPelatihan(penggunaLogin).setVisible(true);
    }//GEN-LAST:event_jButtonPilihPelatihanActionPerformed

    private void jButtonAjukanBantuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjukanBantuanActionPerformed
        this.dispose();
        new AjukanBantuan(penggunaLogin).setVisible(true);
    }//GEN-LAST:event_jButtonAjukanBantuanActionPerformed

    private void jButtonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogOutActionPerformed
        this.dispose();
        new HOMEE().setVisible(true);
    }//GEN-LAST:event_jButtonLogOutActionPerformed

    private void jButtonLihatInsentifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLihatInsentifActionPerformed
        this.dispose();
        new PencairanInsentif(penggunaLogin).setVisible(true);
    }//GEN-LAST:event_jButtonLihatInsentifActionPerformed

    private void jButtonProfilPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProfilPenggunaActionPerformed
        this.dispose();
        new ProfilPengguna_1(penggunaLogin).setVisible(true);
    }//GEN-LAST:event_jButtonProfilPenggunaActionPerformed

    private boolean pastikanLogin() {
        if (penggunaLogin == null) {
            JOptionPane.showMessageDialog(this, "Sesi habis / belum login. Silakan login dulu.");
            this.dispose();
            new Login().setVisible(true);
            return false;
        }
        return true;
    }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjukanBantuan;
    private javax.swing.JButton jButtonLihatInsentif;
    private javax.swing.JButton jButtonLogOut;
    private javax.swing.JButton jButtonPilihPelatihan;
    private javax.swing.JButton jButtonProfilPengguna;
    private javax.swing.JButton jButtonUploadSertifikat;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelHome;
    // End of variables declaration//GEN-END:variables
}
