package View;

import java.text.NumberFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Locale;
import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.ListSelectionModel;

import model.Pelatihan;
import service.PelatihanService;


public class KelolaPelatihan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(KelolaPelatihan.class.getName());

    private final PelatihanService pelSvc = new PelatihanService();
    private DefaultTableModel tblModel;
    private Integer selectedId = null;
    private Integer adminNik;
    private final model.Akun adminLogin;

    private static final DateTimeFormatter DF = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    
    /**
     * Creates new form Kelola_Pelatihan
     */
    public KelolaPelatihan(model.Akun adminLogin) {
        this.adminLogin = adminLogin;
        initComponents();
        this.setLocationRelativeTo(null);
        
        jDateChooser1.setDateFormatString("yyyy-MM-dd");

        if (adminLogin == null) {
            JOptionPane.showMessageDialog(this, "Sesi admin tidak valid, silakan login ulang");
            dispose();
            new Login().setVisible(true);
            return;
        }
        this.adminNik = adminLogin.getNik();
        if (!"admin".equalsIgnoreCase(adminLogin.getPeran())) {
            JOptionPane.showMessageDialog(this, "Akses ditolak: bukan admin");
            dispose();
            return;
        }

        initTable();
        HubungPencarianLangsung();
        muatData(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePelatihan = new javax.swing.JTable();
        jTextFieldPencarian = new javax.swing.JTextField();
        jButtonKembali = new javax.swing.JButton();
        jTextFieldJudul = new javax.swing.JTextField();
        jTextFieldLembaga = new javax.swing.JTextField();
        jTextFieldHarga = new javax.swing.JTextField();
        jButtonTambah = new javax.swing.JButton();
        jButtonPerbarui = new javax.swing.JButton();
        jButtonHapus = new javax.swing.JButton();
        jButtonRefresh = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTablePelatihan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id_pelatihan", "nik_admin", "judul_pelatihan", "lembaga_pelatihan", "periode", "harga_pelatihan"
            }
        ));
        jScrollPane1.setViewportView(jTablePelatihan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 650, 220));

        jTextFieldPencarian.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextFieldPencarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPencarianActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPencarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 270, 40));

        jButtonKembali.setBackground(new java.awt.Color(255, 204, 0));
        jButtonKembali.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jButtonKembali.setForeground(new java.awt.Color(0, 0, 0));
        jButtonKembali.setText("Kembali");
        jButtonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, -1, -1));

        jTextFieldJudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldJudulActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 260, -1));

        jTextFieldLembaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLembagaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldLembaga, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 260, -1));

        jTextFieldHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHargaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 260, -1));

        jButtonTambah.setText("Tambah");
        jButtonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTambahActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        jButtonPerbarui.setText("Perbarui");
        jButtonPerbarui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPerbaruiActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPerbarui, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, -1));

        jButtonHapus.setText("Hapus");
        jButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, -1, -1));

        jButtonRefresh.setText("Refresh");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, -1, -1));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 260, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Kelola Pelatihan.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKembaliActionPerformed
        this.dispose();
        new HomeAdmin(adminLogin).setVisible(true);
    }//GEN-LAST:event_jButtonKembaliActionPerformed

    private void jTextFieldJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldJudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldJudulActionPerformed

    private void jTextFieldPencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPencarianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPencarianActionPerformed

    private void jTextFieldHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHargaActionPerformed

    private void jTextFieldLembagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLembagaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLembagaActionPerformed

    private void jButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambahActionPerformed
        try {
            Pelatihan p = ambilDariForm();
            pelSvc.tambah(p);
            JOptionPane.showMessageDialog(this, "Pelatihan ditambahkan.");
            bersihkanForm();
            muatData(null);
        } catch (IllegalArgumentException iae) {
            JOptionPane.showMessageDialog(this, iae.getMessage(), "Validasi", JOptionPane.WARNING_MESSAGE);
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, "Gagal tambah", ex);
            JOptionPane.showMessageDialog(this, "Gagal menambah: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonTambahActionPerformed

    private void jButtonPerbaruiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPerbaruiActionPerformed
        if (selectedId == null) {
            return;
        }
        try {
            Pelatihan p = ambilDariForm();
            pelSvc.perbarui(p);
            JOptionPane.showMessageDialog(this, "Pelatihan diperbarui.");
            bersihkanForm();
            muatData(null);
        } catch (IllegalArgumentException iae) {
            JOptionPane.showMessageDialog(this, iae.getMessage(), "Validasi", JOptionPane.WARNING_MESSAGE);
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, "Gagal ubah", ex);
            JOptionPane.showMessageDialog(this, "Gagal memperbarui: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonPerbaruiActionPerformed

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
        if (selectedId == null) {
            return;
        }
        int ok = JOptionPane.showConfirmDialog(this, "Hapus pelatihan terpilih?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (ok != JOptionPane.YES_OPTION)
            return;

        try {
            pelSvc.hapus(selectedId);
            JOptionPane.showMessageDialog(this, "Pelatihan dihapus.");
            bersihkanForm();
            muatData(null);
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, "Gagal hapus", ex);
            JOptionPane.showMessageDialog(this, "Gagal menghapus: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonHapusActionPerformed

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        bersihkanForm();
        muatData(null);
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    private void initTable() {
        tblModel = new DefaultTableModel(
            new Object[]{"ID","NIK Admin","Judul","Lembaga","Periode","Harga"}, 0
        ) {
            @Override
            public boolean isCellEditable(int r, int c) { 
                return false; 
            }
            @Override 
            public Class<?> getColumnClass(int c) {
                return switch (c) {
                    case 0,1,5 -> Integer.class;
                    case 4     -> LocalDate.class;
                    default    -> String.class;
                };
            }
        };

        jTablePelatihan.setModel(tblModel);
        jTablePelatihan.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        jTablePelatihan.setDefaultRenderer(LocalDate.class, new DefaultTableCellRenderer() {
            @Override 
            public void setValue(Object value) {
                if (value instanceof LocalDate ld) setText(ld.format(DF));
                else setText(value == null ? "" : value.toString());
            }
        });

        jTablePelatihan.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) isiFormDariTabel();
        });
    }
    
    private void muatData(String q) {
        try {
            tblModel.setRowCount(0);
            var list = pelSvc.temukanSemua();

            String low = (q == null) ? "" : q.trim().toLowerCase();
            boolean doFilter = !low.isEmpty();
            
            var df = (java.text.DecimalFormat)
                    java.text.NumberFormat.getCurrencyInstance(new java.util.Locale("id","ID"));
            df.setMaximumFractionDigits(0);

            for (var p : list) {
                String judul      = p.getJudul()   == null ? "" : p.getJudul();
                String lembaga    = p.getLembaga() == null ? "" : p.getLembaga();
                String periodeStr = p.getPeriode() == null ? "" : p.getPeriode().format(DF);

                if (doFilter) {
                    boolean match = judul.toLowerCase().contains(low)
                                 || lembaga.toLowerCase().contains(low)
                                 || periodeStr.toLowerCase().contains(low);
                    if (!match) 
                        continue;
                }

                tblModel.addRow(new Object[] {
                    p.getIdPelatihan(),
                    p.getNikAdmin(),
                    judul,
                    lembaga,
                    p.getPeriode(),
                    df.format(p.getHarga())
                });
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void isiFormDariTabel() {
        int r = jTablePelatihan.getSelectedRow();
        if (r < 0) { 
            selectedId = null; 
            return; 
        }

        selectedId = (Integer) tblModel.getValueAt(r, 0);
        jTextFieldJudul.setText(String.valueOf(tblModel.getValueAt(r, 2)));
        jTextFieldLembaga.setText(String.valueOf(tblModel.getValueAt(r, 3)));

        Object periodeObj = tblModel.getValueAt(r, 4);
        if (periodeObj instanceof LocalDate ld) {
            Date utilDate = Date.from(ld.atStartOfDay(ZoneId.systemDefault()).toInstant());
            jDateChooser1.setDate(utilDate);
        } else if (periodeObj != null) {
            try {
                LocalDate ld = LocalDate.parse(periodeObj.toString(), DF);
                Date utilDate = Date.from(ld.atStartOfDay(ZoneId.systemDefault()).toInstant());
                jDateChooser1.setDate(utilDate);
            } catch (Exception ignore) {
                jDateChooser1.setDate(null);
            }
        } else {
            jDateChooser1.setDate(null);
        }

        jTextFieldHarga.setText(String.valueOf(tblModel.getValueAt(r, 5)));
    }

    private void bersihkanForm() {
        selectedId = null;
        jTextFieldJudul.setText("");
        jTextFieldLembaga.setText("");
        jTextFieldHarga.setText("");
        jDateChooser1.setDate(null);
        jTablePelatihan.clearSelection();
    }


    private Pelatihan ambilDariForm() {
        String judul   = jTextFieldJudul.getText().trim();
        String lembaga = jTextFieldLembaga.getText().trim();
        String hargaTx = jTextFieldHarga.getText().trim();

        if (judul.isEmpty() || lembaga.isEmpty() || hargaTx.isEmpty())
            throw new IllegalArgumentException("Semua field wajib diisi.");

        Date selectedDate = jDateChooser1.getDate();
        if (selectedDate == null)
            throw new IllegalArgumentException("Tanggal periode wajib dipilih.");

        LocalDate periode = selectedDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

        int harga;
        try { harga = Integer.parseInt(hargaTx); }
        catch (NumberFormatException e) { 
            throw new IllegalArgumentException("Harga harus angka."); }

        Pelatihan p = new Pelatihan();
        if (selectedId != null) p.setIdPelatihan(selectedId);
        p.setJudul(judul);
        p.setLembaga(lembaga);
        p.setPeriode(periode);
        p.setHarga(harga);
        p.setNikAdmin(adminNik);
        return p;
    }

    private void PencarianLangsung() {
        String q = jTextFieldPencarian.getText().trim();
        muatData(q.isEmpty() ? null : q);
    }

    private void HubungPencarianLangsung() {
        jTextFieldPencarian.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override 
            public void insertUpdate(DocumentEvent e) {
                PencarianLangsung(); 
            }
            @Override 
            public void removeUpdate(DocumentEvent e) {
                PencarianLangsung();
            }
            @Override 
            public void changedUpdate(DocumentEvent e) {
                PencarianLangsung(); 
            }
        });
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonKembali;
    private javax.swing.JButton jButtonPerbarui;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JButton jButtonTambah;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePelatihan;
    private javax.swing.JTextField jTextFieldHarga;
    private javax.swing.JTextField jTextFieldJudul;
    private javax.swing.JTextField jTextFieldLembaga;
    private javax.swing.JTextField jTextFieldPencarian;
    // End of variables declaration//GEN-END:variables
}
