package View;

import java.text.NumberFormat;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.DocumentEvent;
import javax.swing.table.DefaultTableModel;
import model.InsentifBaris;
import service.InsentifService;

public class LihatInsentif extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LihatInsentif.class.getName());
    private final InsentifService insentifSvc = new InsentifService();
    private DefaultTableModel tblModel;
    private final model.Akun adminLogin;
    private Integer selectedId = null;
    
    /**
     * Creates new form Daftar_Insentif
     * @param adminLogin
     */
    public LihatInsentif(model.Akun adminLogin) {
        this.adminLogin = adminLogin;
        initComponents();
        this.setLocationRelativeTo(null);
        
        jTextFieldKeterangan.setEditable(false);
        jTextFieldKeterangan.setFocusable(false);
        jTextFieldKeterangan.setBorder(null);
        jTextFieldKeterangan.setOpaque(false);

        initTable();
        HubungPencarianLangsung();
        muatData(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableInsenitf = new javax.swing.JTable();
        jTextFieldPencarian = new javax.swing.JTextField();
        jTextFieldKeterangan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 204, 0));
        jButton1.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 490, -1, -1));

        jTableInsenitf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableInsenitf);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 650, 250));

        jTextFieldPencarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPencarianActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPencarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 320, 30));

        jTextFieldKeterangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldKeteranganActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldKeterangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 390, 40));

        jLabel1.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Lihat Insentif.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        new HomeAdmin(adminLogin).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldPencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPencarianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPencarianActionPerformed

    private void jTextFieldKeteranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldKeteranganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldKeteranganActionPerformed

    private void initTable() {
        tblModel = new DefaultTableModel(
            new Object[]{"ID Insentif","ID Sertifikat","NIK","Nama","Jumlah","Tanggal Cair","Keterangan"}, 0
        ) {
            @Override 
            public boolean isCellEditable(int r,int c){ return false; }
            
            @Override 
            public Class<?> getColumnClass(int c){
                return switch(c){
                    case 0,1,2 -> Integer.class;
                    default -> String.class;
                };
            }
        };
        jTableInsenitf.setModel(tblModel);
        jTableInsenitf.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        jTableInsenitf.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) isiDetailDariTabel();
        });
    }
    
    private void muatData(String keyword) {
        try {
            List<InsentifBaris> list = insentifSvc.cariTampilan(keyword);
            tblModel.setRowCount(0);
            
            var df = (java.text.DecimalFormat)
                    java.text.NumberFormat.getCurrencyInstance(new java.util.Locale("id","ID"));
            df.setMaximumFractionDigits(0);
            
            for (InsentifBaris r : list) {
                tblModel.addRow(new Object[]{
                    r.getIdInsentif(),
                    r.getIdSertifikat(),
                    r.getNikPengguna(),
                    r.getNamaPengguna(),
                    df.format(r.getJumlahInsentif()),
                    (r.getTanggalCair()==null? "-" : r.getTanggalCair().toString()),
                    r.getKeterangan()
                });
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Gagal memuat insentif: " + ex.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private String formatRupiah(Integer n){
        if (n==null) 
            return "-";
        NumberFormat nf = NumberFormat.getCurrencyInstance(new Locale("id","ID"));
        return nf.format(n);
    }
    
    private void isiDetailDariTabel() {
        int r = jTableInsenitf.getSelectedRow();
        if (r < 0) { 
            selectedId = null; 
            jTextFieldKeterangan.setText("");
            return; 
        }
        selectedId = (Integer) tblModel.getValueAt(r, 0);

        try {
            List<InsentifBaris> rows = insentifSvc.cariTampilan(null);
            InsentifBaris row = rows.stream()
                    .filter(x -> x.getIdInsentif().equals(selectedId))
                    .findFirst()
                    .orElse(null);

            jTextFieldKeterangan.setText(row == null ? "" : row.getKeterangan());
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.WARNING, "Gagal baca detail insentif", ex);
            jTextFieldKeterangan.setText("");
        }
    }

    private void PencarianLangsung() {
        String q = jTextFieldPencarian.getText().trim();
        muatData(q.isEmpty() ? null : q);
    }

    private void HubungPencarianLangsung() {
        jTextFieldPencarian.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override 
            public void insertUpdate(DocumentEvent e) {
                PencarianLangsung(); 
            }
            @Override 
            public void removeUpdate(DocumentEvent e) {
                PencarianLangsung();
            }
            @Override 
            public void changedUpdate(DocumentEvent e) {
                PencarianLangsung(); 
            }
        });
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableInsenitf;
    private javax.swing.JTextField jTextFieldKeterangan;
    private javax.swing.JTextField jTextFieldPencarian;
    // End of variables declaration//GEN-END:variables
}
