/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Akun;
import service.InsentifService;

/**
 *
 * @author asus_
 */
public class PencairanInsentif extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(PencairanInsentif.class.getName());

    private final InsentifService insentifSvc = new InsentifService();
    private final Akun penggunaLogin;
    private DefaultTableModel tblModel;

    private static final DateTimeFormatter DF =
        DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");

    public PencairanInsentif(Akun penggunaLogin) {
        this.penggunaLogin = penggunaLogin;
        initComponents();
        this.setLocationRelativeTo(null);
        initTable();
        muatData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 600, 230));

        jButton1.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jButton1.setText("Cairkan Insentif");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 160, 30));

        jButton2.setBackground(new java.awt.Color(255, 204, 51));
        jButton2.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jButton2.setText("Kembali");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 100, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Insentif.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        new HomePengguna(penggunaLogin).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cairkan();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void initTable() {
        tblModel = new DefaultTableModel(
            new Object[]{"ID", "Jumlah", "Tanggal Cair", "Keterangan"}, 0
        ) {
            @Override 
            public boolean isCellEditable(int r, int c) { return false; }
        };
        jTable1.setModel(tblModel);
    }

    private String rupiah(int v) {
        return "Rp " + String.format("%,d", v).replace(",", ".");
    }

    private void muatData() {
        tblModel.setRowCount(0);
        var list = insentifSvc.getInsentifPengguna(penggunaLogin.getNik());
        
        var df = (java.text.DecimalFormat)
                java.text.NumberFormat.getCurrencyInstance(new java.util.Locale("id","ID"));
        df.setMaximumFractionDigits(0);

        for (var row : list) {
            
            Object idObj = row[0];
            int id = (idObj instanceof Number) ? ((Number) idObj).intValue() : Integer.parseInt(idObj.toString());

            Object jumlahObj = row[1];
            int jumlahInsentif = (jumlahObj instanceof Number) ? ((Number) jumlahObj).intValue() : Integer.parseInt(jumlahObj.toString());

            Object tglObj = row[2];
            String tglStr = "-";
            if (tglObj != null) {
                if (tglObj instanceof java.time.LocalDate d) {
                    tglStr = d.toString();
                } else if (tglObj instanceof java.sql.Date d) {
                    tglStr = d.toLocalDate().toString();
                } else {
                    tglStr = tglObj.toString();
                }
            }

            String ket = (row[3] == null) ? "" : row[3].toString();

            tblModel.addRow(new Object[]{
                id,
                df.format(jumlahInsentif),
                tglStr,
                ket
            });
        }
    }

    private void cairkan() {
        int row = jTable1.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Pilih insentif dulu.");
            return;
        }

        int idIns = Integer.parseInt(tblModel.getValueAt(row, 0).toString());
        String jmlStr = tblModel.getValueAt(row, 1).toString();
        int jml = Integer.parseInt(jmlStr.replace("Rp ", "").replace(".", ""));

        if (jml <= 0) {
            JOptionPane.showMessageDialog(this, "Insentif sudah dicairkan.");
            return;
        }

        String noRek = JOptionPane.showInputDialog(
            this, "Masukkan No Rekening tujuan:"
        );
        if (noRek == null || noRek.isBlank()) {
            JOptionPane.showMessageDialog(this, "Nomor rekening wajib diisi.");
            return;
        }

        try {
            insentifSvc.cairkanLangsung(idIns);
            JOptionPane.showMessageDialog(
                this,
                "Insentif berhasil dicairkan ke rekening " + noRek,
                "Sukses",
                JOptionPane.INFORMATION_MESSAGE
            );
            muatData();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
