package View;

import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import service.PelatihanService;

public class PilihanPelatihan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PilihanPelatihan.class.getName());
    private final PelatihanService pelatihanSvc = new PelatihanService();
    private final model.Akun penggunaLogin;
    private javax.swing.table.DefaultTableModel tblModel;
    
    private static final java.time.format.DateTimeFormatter DF =
        java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd");

    /**
     * Creates new form Pilihan_Pelatihan
     */
    public PilihanPelatihan(model.Akun penggunaLogin) {
        this.penggunaLogin = penggunaLogin;
        initComponents();
        this.setLocationRelativeTo(null);
        initTablePelatihan();
        HubungPencarianLangsung();
        muatData(null);
        pasangListenerRow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextFieldJudul = new javax.swing.JTextField();
        jTextFieldLembaga = new javax.swing.JTextField();
        jTextFieldPeriode = new javax.swing.JTextField();
        jTextFieldHarga = new javax.swing.JTextField();
        jTextFieldPencarian = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jButton1.setText("Beli Pelatihan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, 140, 30));

        jButton2.setBackground(new java.awt.Color(255, 204, 0));
        jButton2.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jButton2.setText("Kembali");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 510, 100, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 620, 260));

        jTextFieldJudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldJudulActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 200, 30));
        getContentPane().add(jTextFieldLembaga, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 180, 30));
        getContentPane().add(jTextFieldPeriode, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 110, 30));
        getContentPane().add(jTextFieldHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 420, 100, 30));

        jTextFieldPencarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPencarianActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPencarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 250, 30));

        jLabel1.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Pilih Pelatihan.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        final int nik = penggunaLogin.getNik();

        if (!pelatihanSvc.bolehBeliPelatihan(nik)) {
            JOptionPane.showMessageDialog(
                this,
                "Pengajuan belum DITERIMA. Tidak bisa membeli pelatihan.",
                "Tidak Bisa Membeli",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        
        int row = jTable1.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Pilih dulu pelatihan di tabel.");
            return;
        }

        int idPel;
        String judul;
        int harga;
        try {
            idPel = (int) jTable1.getValueAt(row, 0);
            judul = String.valueOf(jTable1.getValueAt(row, 1));
            Object hargaObj = jTable1.getValueAt(row, 4);
            harga = (hargaObj instanceof Number) ? ((Number) hargaObj).intValue()
                                                 : Integer.parseInt(String.valueOf(hargaObj));
        } catch (Exception parseEx) {
            JOptionPane.showMessageDialog(this, "Struktur tabel tidak sesuai: " + parseEx.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            if (pelatihanSvc.sudahPernahBeli(nik, idPel)) {
                JOptionPane.showMessageDialog(
                    this,
                    "Pelatihan \"" + judul + "\" sudah pernah kamu beli.",
                    "Informasi",
                    JOptionPane.INFORMATION_MESSAGE
                );
                return;
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Gagal cek status pembelian: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int ok = JOptionPane.showConfirmDialog(
            this,
            "Beli \"" + judul + "\" seharga " + formatRupiah(harga) + " ?",
            "Konfirmasi Pembelian",
            JOptionPane.YES_NO_OPTION
        );
        if (ok != JOptionPane.YES_OPTION) 
            return;

        try {
            pelatihanSvc.beliPelatihan(nik, idPel);
            JOptionPane.showMessageDialog(this, "Pembelian berhasil. Saldo terpotong.", "Sukses",
                    JOptionPane.INFORMATION_MESSAGE);

            muatData(null);
            JOptionPane.showMessageDialog(this, 
                    "Silakan cek riwayat pada menu Profil.", 
                    "Sukses", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (IllegalStateException ex) {
 
            String msg = ex.getMessage();
            if ("INSUFFICIENT".equalsIgnoreCase(msg)) {
                JOptionPane.showMessageDialog(this,
                        "Saldo tidak cukup untuk membeli pelatihan ini.",
                        "Saldo Tidak Cukup",
                        JOptionPane.WARNING_MESSAGE);
            } else if (msg != null && msg.toLowerCase().contains("sudah")) {
                JOptionPane.showMessageDialog(this, msg, "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, msg, "Gagal", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        new HomePengguna(penggunaLogin).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextFieldJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldJudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldJudulActionPerformed

    private void jTextFieldPencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPencarianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPencarianActionPerformed

    private void initTablePelatihan() {
        tblModel = new javax.swing.table.DefaultTableModel(
            new Object[]{"ID", "Judul", "Lembaga", "Periode", "Harga"}, 0
        ){
            @Override 
            public boolean isCellEditable(int r, int c) { 
                return false; 
            }
        };
        jTable1.setModel(tblModel);
        jTable1.getTableHeader().setReorderingAllowed(false);
    }

    private String rupiah(Integer v){
        int x = (v == null ? 0 : v);
        return ("Rp " + String.format("%,d", x)).replace(',', '.');
    }

    private void pasangListenerRow() {
        jTable1.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && jTable1.getSelectedRow() >= 0) {
                int row = jTable1.getSelectedRow();
                jTextFieldJudul.setText(jTable1.getValueAt(row, 1).toString());
                jTextFieldLembaga.setText(jTable1.getValueAt(row, 2).toString());
                jTextFieldPeriode.setText(jTable1.getValueAt(row, 3).toString());
                jTextFieldHarga.setText(jTable1.getValueAt(row, 4).toString());
            }
        });
    }
    
    private void muatData(String q) {
        try {
            tblModel.setRowCount(0);
            var list = pelatihanSvc.temukanSemua();

            String low = (q == null) ? "" : q.trim().toLowerCase();
            boolean doFilter = !low.isEmpty();
            
            var df = (java.text.DecimalFormat)
                    java.text.NumberFormat.getCurrencyInstance(new java.util.Locale("id","ID"));
            df.setMaximumFractionDigits(0);

            for (var p : list) {
                String judul   = p.getJudul()   == null ? "" : p.getJudul();
                String lembaga = p.getLembaga() == null ? "" : p.getLembaga();
                String periode = (p.getPeriode() == null)
                        ? "" 
                        : p.getPeriode().format(DF);

                if (doFilter) {
                    boolean match = judul.toLowerCase().contains(low)
                                 || lembaga.toLowerCase().contains(low)
                                 || periode.toLowerCase().contains(low);
                    if (!match) 
                        continue;
                }

                tblModel.addRow(new Object[] {
                    p.getIdPelatihan(),
                    judul,
                    lembaga,
                    periode,
                    df.format(p.getHarga())
                });
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(
                this,
                "Gagal memuat data: " + ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }

    private void PencarianLangsung() {
        String q = jTextFieldPencarian.getText().trim();
        muatData(q.isEmpty() ? null : q);
    }

    private void HubungPencarianLangsung() {
        jTextFieldPencarian.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override 
            public void insertUpdate(DocumentEvent e) {
                PencarianLangsung(); 
            }
            @Override 
            public void removeUpdate(DocumentEvent e) {
                PencarianLangsung();
            }
            @Override 
            public void changedUpdate(DocumentEvent e) {
                PencarianLangsung(); 
            }
        });
    }
    
    private static String formatRupiah(int angka) {
        var locale = new java.util.Locale("id", "ID");
        var fmt = (java.text.DecimalFormat) java.text.NumberFormat.getCurrencyInstance(locale);
        fmt.setMaximumFractionDigits(0);
        return fmt.format(angka);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldHarga;
    private javax.swing.JTextField jTextFieldJudul;
    private javax.swing.JTextField jTextFieldLembaga;
    private javax.swing.JTextField jTextFieldPencarian;
    private javax.swing.JTextField jTextFieldPeriode;
    // End of variables declaration//GEN-END:variables
}
