package View;

import model.Akun;

public class ProfilPengguna_1 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistrasiAkun.class.getName());
    private final service.PenggunaService penggunaService = new service.PenggunaService();
    private final service.PelatihanService pelSvc = new service.PelatihanService();

    private final Akun penggunaLogin;
    /**
     * Creates new form Registrasi
     * @param penggunaLogin
     */
    public ProfilPengguna_1(model.Akun penggunaLogin) {
        if (penggunaLogin == null) 
            throw new IllegalArgumentException("penggunaLogin null");
        this.penggunaLogin = penggunaLogin;
        initComponents();
        this.setLocationRelativeTo(null);
        FieldHanyaTampilkan();
        isiSaldo(); 
        isiProfil(); 
        muatTabelPelatihan();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNama = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldNIK = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextFieldPenghasilan = new javax.swing.JTextField();
        jTextFieldPekerjaan = new javax.swing.JTextField();
        jTextFieldAlamat = new javax.swing.JTextField();
        jButtonKembali = new javax.swing.JButton();
        jTextFieldSaldoAkun = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldNama.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextFieldNama.setToolTipText("");
        jTextFieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNamaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 240, 30));

        jTextFieldEmail.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 240, 30));

        jTextFieldNIK.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextFieldNIK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNIKActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNIK, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 240, 30));

        jPasswordField1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 240, 30));

        jTextFieldPenghasilan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextFieldPenghasilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPenghasilanActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPenghasilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 240, 30));

        jTextFieldPekerjaan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextFieldPekerjaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPekerjaanActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPekerjaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 240, 30));

        jTextFieldAlamat.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextFieldAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAlamatActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 530, 30));

        jButtonKembali.setBackground(new java.awt.Color(255, 204, 0));
        jButtonKembali.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jButtonKembali.setText("Kembali");
        jButtonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 520, -1, -1));

        jTextFieldSaldoAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSaldoAkunActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldSaldoAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 110, 20));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 530, 80));

        jLabel1.setBackground(new java.awt.Color(255, 204, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Data Pengguna.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAlamatActionPerformed

    private void jButtonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKembaliActionPerformed
        this.dispose();
        new HomePengguna(penggunaLogin).setVisible(true);
    }//GEN-LAST:event_jButtonKembaliActionPerformed

    private void jTextFieldNIKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNIKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNIKActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextFieldPenghasilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPenghasilanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPenghasilanActionPerformed

    private void jTextFieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNamaActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jTextFieldPekerjaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPekerjaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPekerjaanActionPerformed

    private void jTextFieldSaldoAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSaldoAkunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSaldoAkunActionPerformed

    private void FieldHanyaTampilkan() {
        jTextFieldNIK.setEditable(false);         jTextFieldNIK.setFocusable(false);
        jTextFieldNama.setEditable(false);        jTextFieldNama.setFocusable(false);
        jTextFieldEmail.setEditable(false);       jTextFieldEmail.setFocusable(false);
        jPasswordField1.setEditable(false);       jPasswordField1.setFocusable(false);
        jTextFieldPenghasilan.setEditable(false); jTextFieldPenghasilan.setFocusable(false);
        jTextFieldPekerjaan.setEditable(false);   jTextFieldPekerjaan.setFocusable(false);
        jTextFieldAlamat.setEditable(false);      jTextFieldAlamat.setFocusable(false);
    }
    
    private void isiSaldo() {
        var pg = penggunaService.temukan(penggunaLogin.getNik());

        Integer saldo = (pg != null && pg.getSaldoAkun() != null)
                        ? pg.getSaldoAkun()
                        : 0;

        java.text.DecimalFormat df = (java.text.DecimalFormat) java.text.NumberFormat.getCurrencyInstance(new java.util.Locale("id", "ID"));
        df.setMaximumFractionDigits(0);

        String saldoRupiah = df.format(saldo);

        jTextFieldSaldoAkun.setText(saldoRupiah);
        jTextFieldSaldoAkun.setEditable(false);
        jTextFieldSaldoAkun.setFocusable(false);
        jTextFieldSaldoAkun.setBorder(null);
    }

    private void isiProfil() {
        jTextFieldNIK.setText(String.valueOf(penggunaLogin.getNik()));
        jTextFieldNama.setText(penggunaLogin.getNama());
        jTextFieldEmail.setText(penggunaLogin.getEmail());
        jPasswordField1.setText(penggunaLogin.getPassword());

        var pg = penggunaService.temukan(penggunaLogin.getNik());
        if (pg != null) {
            jTextFieldPekerjaan.setText(nullToEmpty(pg.getPekerjaan()));
            jTextFieldPenghasilan.setText(pg.getPenghasilan() == null ? "" : String.valueOf(pg.getPenghasilan()));
            jTextFieldAlamat.setText(nullToEmpty(pg.getAlamat()));
        } else {
            jTextFieldPekerjaan.setText("");
            jTextFieldPenghasilan.setText("");
            jTextFieldAlamat.setText("");
        }
    }
    
    private void muatTabelPelatihan() {
        String[] kolom = {"Judul Pelatihan", "Lembaga", "Periode", "Harga"};
        var model = new javax.swing.table.DefaultTableModel(kolom, 0) {
            @Override
            public boolean isCellEditable(int r, int c) { return false; }
        };

        var list = pelSvc.getRiwayatPelatihanDariNik(penggunaLogin.getNik());

        var df = (java.text.DecimalFormat)
                java.text.NumberFormat.getCurrencyInstance(new java.util.Locale("id","ID"));
        df.setMaximumFractionDigits(0);

        for (var row : list) {
            String judul   = (String) row[1];
            String lembaga = (String) row[2];
            java.time.LocalDate periode = (java.time.LocalDate) row[3];
            Integer harga = (Integer) row[4];

            model.addRow(new Object[]{
                judul,
                lembaga,
                periode.toString(),
                df.format(harga)
            });
        }

        jTable1.setModel(model);
    }


    private static String nullToEmpty(String s) { 
        return s == null ? "" : s; 
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonKembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldAlamat;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNIK;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTextField jTextFieldPekerjaan;
    private javax.swing.JTextField jTextFieldPenghasilan;
    private javax.swing.JTextField jTextFieldSaldoAkun;
    // End of variables declaration//GEN-END:variables
}
