package View;

import service.AuthService;

public class RegistrasiAkun extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistrasiAkun.class.getName());
    private final AuthService authService = new AuthService();

    /**
     * Creates new form Registrasi
     */
    public RegistrasiAkun() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNama = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldNIK = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextFieldPenghasilan = new javax.swing.JTextField();
        jTextFieldPekerjaan = new javax.swing.JTextField();
        jTextFieldAlamat = new javax.swing.JTextField();
        jButtonKembali = new javax.swing.JButton();
        jButtonRegis = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldNama.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldNama.setToolTipText("");
        jTextFieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNamaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 240, 30));

        jTextFieldEmail.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 240, 30));

        jTextFieldNIK.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldNIK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNIKActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNIK, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 240, 30));

        jPasswordField1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 240, 30));

        jTextFieldPenghasilan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldPenghasilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPenghasilanActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPenghasilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 240, 30));

        jTextFieldPekerjaan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldPekerjaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPekerjaanActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPekerjaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 240, 30));

        jTextFieldAlamat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAlamatActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 530, 30));

        jButtonKembali.setBackground(new java.awt.Color(255, 204, 0));
        jButtonKembali.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jButtonKembali.setText("Kembali");
        jButtonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, -1, -1));

        jButtonRegis.setBackground(new java.awt.Color(255, 204, 0));
        jButtonRegis.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jButtonRegis.setText("Registrasi");
        jButtonRegis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegis, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 204, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Registrasi.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAlamatActionPerformed

    private void jButtonRegisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisActionPerformed
        String nikTxt       = jTextFieldNIK.getText().trim();
        String nama         = jTextFieldNama.getText().trim();
        String email        = jTextFieldEmail.getText().trim();
        String pass         = new String(jPasswordField1.getPassword());
        String alamat       = jTextFieldAlamat.getText().trim();
        String pekerjaan    = jTextFieldPekerjaan.getText().trim();
        String penghasilanT = jTextFieldPenghasilan.getText().trim();

        if (nikTxt.isEmpty() || nama.isEmpty() || email.isEmpty() || pass.isEmpty()
                || alamat.isEmpty() || pekerjaan.isEmpty() || penghasilanT.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Semua form wajib diisi.");
            return;
        }

        Integer nik, penghasilan;
        try {
            nik = Integer.parseInt(nikTxt);
            penghasilan = Integer.parseInt(penghasilanT);
            if (nik <= 0 || penghasilan < 0) throw new NumberFormatException();
        } catch (NumberFormatException nfe) {
            javax.swing.JOptionPane.showMessageDialog(this, "NIK & Penghasilan harus berupa angka valid.");
            return;
        }

        if (!email.matches("^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Format email tidak valid.");
            return;
        }

        try {
            service.AuthService svc = new service.AuthService();

            if (svc.nikSudahDipakai(nik)) {
                javax.swing.JOptionPane.showMessageDialog(this, "NIK sudah terdaftar.");
                return;
            }
            if (svc.emailSudahDipakai(email)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Email sudah terdaftar.");
                return;
            }

            svc.registerPengguna(
                    nik, nama, email, pass,
                    alamat, pekerjaan, penghasilan
            );

            javax.swing.JOptionPane.showMessageDialog(this, "Registrasi berhasil. Silakan login.");
            this.dispose();
            new View.Login().setVisible(true);

        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, "Gagal registrasi", ex);
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal registrasi: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonRegisActionPerformed

    private void jButtonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKembaliActionPerformed
        this.dispose();
        new HOMEE().setVisible(true);
    }//GEN-LAST:event_jButtonKembaliActionPerformed

    private void jTextFieldNIKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNIKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNIKActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextFieldPenghasilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPenghasilanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPenghasilanActionPerformed

    private void jTextFieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNamaActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jTextFieldPekerjaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPekerjaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPekerjaanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegistrasiAkun().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonKembali;
    private javax.swing.JButton jButtonRegis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextFieldAlamat;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNIK;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTextField jTextFieldPekerjaan;
    private javax.swing.JTextField jTextFieldPenghasilan;
    // End of variables declaration//GEN-END:variables
}
