
package View;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Akun;
import service.SertifikatService;

public class Sertifikat_dan_DataDiri extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Sertifikat_dan_DataDiri.class.getName());
    private final Akun penggunaLogin;
    private final SertifikatService sertifSvc = new SertifikatService();
    private DefaultTableModel tblModel;
    private final service.PelatihanService pelatihanSvc = new service.PelatihanService();
    private final javax.swing.JComboBox<PelItem> cmbPelatihan;
    private final java.util.List<Integer> rowIds = new java.util.ArrayList<>();

    private static final class PelItem {
        final Integer id; 
        final String label;
        PelItem(Integer id, String label){ this.id = id; this.label = label; }
        @Override 
        public String toString(){
            return label; 
        }
    }
    
    public Sertifikat_dan_DataDiri(Akun penggunaLogin) {
        this.penggunaLogin = penggunaLogin;
        initComponents();

        this.cmbPelatihan = (javax.swing.JComboBox<PelItem>) (javax.swing.JComboBox<?>) this.jComboBox1;

        this.setLocationRelativeTo(null);
        initTable();
        
        jButtonOKE.setEnabled(true);
        jTextFieldLINKSertif.setEditable(true);

        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override public void mouseClicked(java.awt.event.MouseEvent e) {
                if (e.getClickCount() == 2 && jTable1.getSelectedRow() >= 0) {
                    jButtonLihatLINKActionPerformed(null);
                }
            }
        });

        muatComboPelatihan();
        muatData();
        pasangRowListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonKembali = new javax.swing.JButton();
        jTextFieldLINKSertif = new javax.swing.JTextField();
        jButtonOKE = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonLihatLINK = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonKembali.setBackground(new java.awt.Color(255, 204, 0));
        jButtonKembali.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jButtonKembali.setText("Kembali");
        jButtonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, 110, 40));

        jTextFieldLINKSertif.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        jTextFieldLINKSertif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLINKSertifActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldLINKSertif, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 290, -1));

        jButtonOKE.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jButtonOKE.setText("OK");
        jButtonOKE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKEActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOKE, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 60, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 570, 200));

        jButtonLihatLINK.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jButtonLihatLINK.setText("KLIK LINK DISINI!");
        jButtonLihatLINK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLihatLINKActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLihatLINK, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, 150, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 190, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Upload Sertifikat.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKembaliActionPerformed
       this.dispose();
        new HomePengguna(penggunaLogin).setVisible(true);
    }//GEN-LAST:event_jButtonKembaliActionPerformed

    private void jButtonOKEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKEActionPerformed
        String link = jTextFieldLINKSertif.getText().trim();
        if (link.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Masukkan link sertifikat.");
            return;
        }
        if (!(link.startsWith("http://") || link.startsWith("https://"))) {
            link = "https://" + link;
        }

        try {
            int sel = jTable1.getSelectedRow();

            if (sel >= 0) {
                String st = String.valueOf(tblModel.getValueAt(sel, 1));
                if ("DITOLAK".equalsIgnoreCase(st)) {
                    Integer id = rowIds.get(sel);
                    sertifSvc.resubmitLinkDitolak(id, link);
                    javax.swing.JOptionPane.showMessageDialog(this, "Link dikirim ulang. Status menjadi MENUNGGU.");
                    jTextFieldLINKSertif.setText("");
                    muatData();
                    return;
                }
            }
            
            if (sertifSvc.hasPendingDariNik(penggunaLogin.getNik())) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Masih ada sertifikat MENUNGGU. Tunggu verifikasi selesai sebelum upload lagi.");
                return;
            }

            PelItem item = (PelItem) cmbPelatihan.getSelectedItem();
            if (item == null || item.id == null) {
                sertifSvc.tambahLinkSertifikat(penggunaLogin.getNik(), link);
            } else {
                sertifSvc.tambahLinkSertifikatDariPelatihan(penggunaLogin.getNik(), item.id, link);
            }
            javax.swing.JOptionPane.showMessageDialog(this, "Link sertifikat di-upload. Menunggu verifikasi.");
            jTextFieldLINKSertif.setText("");
            muatData();

        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, "Upload/Kirim ulang link", ex);
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButtonOKEActionPerformed

    private void jTextFieldLINKSertifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLINKSertifActionPerformed

    }//GEN-LAST:event_jTextFieldLINKSertifActionPerformed

    private void jButtonLihatLINKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLihatLINKActionPerformed
        int r = jTable1.getSelectedRow();
        if (r < 0) {
            JOptionPane.showMessageDialog(this, "Pilih baris di tabel.");
            return;
        }

        String link = String.valueOf(jTable1.getValueAt(r, 0)).trim();

        if (link.isEmpty() || link.equalsIgnoreCase("null")) {
            JOptionPane.showMessageDialog(this, "Baris ini belum memiliki link.");
            return;
        }

        if (!(link.startsWith("http://") || link.startsWith("https://"))) {
            link = "https://" + link;
        }

        try {
            java.net.URI uri = new java.net.URI(link);
            if (!java.awt.Desktop.isDesktopSupported()) {
                JOptionPane.showMessageDialog(this, "Desktop tidak mendukung buka browser otomatis.");
                return;
            }
            java.awt.Desktop.getDesktop().browse(uri);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                "Link tidak valid: " + link,
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_jButtonLihatLINKActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void initTable() {
        tblModel = new DefaultTableModel(
            new Object[]{"Link Sertifikat", "Status", "Tanggal Upload"}, 0
        ){
            @Override 
            public boolean isCellEditable(int r, int c) { 
                return false; 
            }
        };

        jTable1.setModel(tblModel);
        jTable1.getTableHeader().setReorderingAllowed(false);
    }

    private void muatData() {
        tblModel.setRowCount(0);
        rowIds.clear();

        var rows = sertifSvc.daftarSertifikatPengguna(penggunaLogin.getNik());
        for (Object[] r : rows) {
            Integer id   = (Integer) r[0];
            String  link = (String)  r[2];
            String  stt  = (String)  r[3];
            Object  tglO = r[4];

            String tglStr = "-";
            if (tglO instanceof java.time.LocalDate d) tglStr = d.toString();
            else if (tglO != null) tglStr = String.valueOf(tglO);

            rowIds.add(id);
            tblModel.addRow(new Object[]{ link == null ? "" : link, stt, tglStr });
        }

        onRowSelected();
    }

    private void pasangRowListener() {
        jTable1.getSelectionModel().addListSelectionListener((e) -> {
            if (e.getValueIsAdjusting()) return;
            onRowSelected();
        });
    }

    private void onRowSelected() {
        int r = jTable1.getSelectedRow();
        if (r < 0) {
            // tetap bisa upload baru
            jButtonOKE.setEnabled(true);
            jTextFieldLINKSertif.setEditable(true);
            jTextFieldLINKSertif.setText("");
            return;
        }
        String status = String.valueOf(tblModel.getValueAt(r, 1)); // Status
        String link   = String.valueOf(tblModel.getValueAt(r, 0)); // Link
        jTextFieldLINKSertif.setText("null".equalsIgnoreCase(link) ? "" : link);

        // Selalu boleh mengetik; kalau status DITOLAK = kirim ulang, selain itu = upload baru
        jButtonOKE.setEnabled(true);
        jTextFieldLINKSertif.setEditable(true);
    }


    private void simpanLink() {
        String link = jTextFieldLINKSertif.getText().trim();
        if (link.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan link sertifikat terlebih dahulu.");
            return;
        }
        if (!(link.startsWith("http://") || link.startsWith("https://"))) {
            int ok = JOptionPane.showConfirmDialog(
                this, "Link tidak diawali http/https. Lanjutkan simpan?", 
                "Konfirmasi", JOptionPane.YES_NO_OPTION
            );
            if (ok != JOptionPane.YES_OPTION) return;
        }

        try {
            PelItem item = (PelItem) cmbPelatihan.getSelectedItem();
            if (item == null || item.id == null) {

                sertifSvc.tambahLinkSertifikat(penggunaLogin.getNik(), link);
            } else {

                sertifSvc.tambahLinkSertifikatDariPelatihan(penggunaLogin.getNik(), item.id, link);
            }
            JOptionPane.showMessageDialog(this, "Link sertifikat tersimpan.");
            jTextFieldLINKSertif.setText("");
            muatData();
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, "Gagal simpan link", ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }


    private void muatComboPelatihan() {
        var model = new javax.swing.DefaultComboBoxModel<PelItem>();
        model.addElement(new PelItem(null, "Tidak terkait pelatihan")); // item 0

        try {
            var list = pelatihanSvc.getRiwayatPelatihanDariNik(penggunaLogin.getNik());
            for (Object[] r : list) {
                
                Integer id = null;
                Object idObj = r[0];
                if (idObj instanceof Number n) id = n.intValue();
                else if (idObj != null) id = Integer.valueOf(idObj.toString());

                String judul   = (String)  r[1];
                String lembaga = (String)  r[2];

                String label = (judul == null ? "(Tanpa judul)" : judul) +
                               " – " + (lembaga == null ? "" : lembaga);
                model.addElement(new PelItem(id, label));
            }
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, "Load combo pelatihan", ex);
        }

        cmbPelatihan.setModel(model);
        cmbPelatihan.setSelectedIndex(0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonKembali;
    private javax.swing.JButton jButtonLihatLINK;
    private javax.swing.JButton jButtonOKE;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldLINKSertif;
    // End of variables declaration//GEN-END:variables
}
