package View;

import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.table.DefaultTableModel;


public class VerifikasiSertifikat extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VerifikasiSertifikat.class.getName());

    private final model.Akun adminLogin;
    private final service.SertifikatService sertifikatSvc = new service.SertifikatService();

    private DefaultTableModel tblModel;
    private Integer selectedId = null;
    private String  linkTerpilih = "";

    public VerifikasiSertifikat(model.Akun adminLogin) {
        this.adminLogin = adminLogin;
        initComponents();
        setLocationRelativeTo(null);

        initTable();
        hubungPencarianLangsung();
        muatData(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldPencarian = new javax.swing.JTextField();
        jButtonKembali = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSertifikat = new javax.swing.JTable();
        jButtonDiterima = new javax.swing.JButton();
        jButtonDitolak = new javax.swing.JButton();
        jButtonKlikLink = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldPencarian.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextFieldPencarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPencarianActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPencarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 250, 30));

        jButtonKembali.setBackground(new java.awt.Color(255, 204, 0));
        jButtonKembali.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jButtonKembali.setText("Kembali");
        jButtonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 510, -1, -1));

        jTableSertifikat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableSertifikat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 650, 260));

        jButtonDiterima.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jButtonDiterima.setForeground(new java.awt.Color(0, 255, 51));
        jButtonDiterima.setText("Diterima");
        jButtonDiterima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDiterimaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDiterima, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));

        jButtonDitolak.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jButtonDitolak.setForeground(new java.awt.Color(255, 51, 0));
        jButtonDitolak.setText("Ditolak");
        jButtonDitolak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDitolakActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDitolak, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, -1, -1));

        jButtonKlikLink.setText("KLIK LINK DISINI");
        jButtonKlikLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKlikLinkActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonKlikLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 130, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Verifikasi Sertifikat.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKembaliActionPerformed
        this.dispose();
        new HomeAdmin(adminLogin).setVisible(true);
    }//GEN-LAST:event_jButtonKembaliActionPerformed

    private void jButtonDiterimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDiterimaActionPerformed
        int r = jTableSertifikat.getSelectedRow();
        if (r < 0 || selectedId == null) {
            JOptionPane.showMessageDialog(this, "Pilih data di tabel.");
            return;
        }
        String st = String.valueOf(tblModel.getValueAt(r, 4));
        if ("DITERIMA".equalsIgnoreCase(st)) {
            JOptionPane.showMessageDialog(this, "Status sudah DITERIMA dan tidak dapat diubah.");
            return;
        }
        int ok = JOptionPane.showConfirmDialog(this,
                "Tetapkan DITERIMA? Insentif Rp3.500.000 akan dibuat.",
                "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (ok != JOptionPane.YES_OPTION) return;

        try {
            sertifikatSvc.verifikasi(selectedId, true, null);
            JOptionPane.showMessageDialog(this, "Berhasil diset DITERIMA. Insentif dibuat.");
            pencarianLangsung();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            logger.log(java.util.logging.Level.SEVERE, "Diterima", ex);
        }
    }//GEN-LAST:event_jButtonDiterimaActionPerformed

    private void jButtonDitolakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDitolakActionPerformed
        int r = jTableSertifikat.getSelectedRow();
        if (r < 0 || selectedId == null) {
            JOptionPane.showMessageDialog(this, "Pilih data di tabel.");
            return;
        }
        String st = String.valueOf(tblModel.getValueAt(r, 4));
        if ("DITERIMA".equalsIgnoreCase(st)) {
            JOptionPane.showMessageDialog(this, "Status sudah DITERIMA dan tidak dapat diubah.");
            return;
        }
        int ok = JOptionPane.showConfirmDialog(this, "Tetapkan DITOLAK?", "Konfirmasi",
                JOptionPane.YES_NO_OPTION);
        if (ok != JOptionPane.YES_OPTION) return;

        try {
            sertifikatSvc.verifikasi(selectedId, false, null);
            JOptionPane.showMessageDialog(this, "Status diubah menjadi DITOLAK.");
            pencarianLangsung();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            logger.log(java.util.logging.Level.SEVERE, "Ditolak", ex);
        }
    }//GEN-LAST:event_jButtonDitolakActionPerformed

    private void jTextFieldPencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPencarianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPencarianActionPerformed

    private void jButtonKlikLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKlikLinkActionPerformed
        int r = jTableSertifikat.getSelectedRow();
        if (r < 0) {
            JOptionPane.showMessageDialog(this, "Pilih baris di tabel terlebih dahulu.");
            return;
        }

        int linkCol = jTableSertifikat.getColumnModel().getColumnIndex("Link");
        String link = String.valueOf(tblModel.getValueAt(r, linkCol));

        if (link == null || link.isBlank() || "null".equalsIgnoreCase(link)) {
            JOptionPane.showMessageDialog(this, "Tidak ada link sertifikat pada baris ini.");
            return;
        }

        if (!(link.startsWith("http://") || link.startsWith("https://"))) {
            link = "https://" + link.trim();
        }

        try {
            java.awt.Desktop.getDesktop().browse(new java.net.URI(link));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Gagal membuka link: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonKlikLinkActionPerformed
    
    private void initTable() {
        tblModel = new javax.swing.table.DefaultTableModel(
                    new Object[]{"ID","NIK","Nama", "ID Pelatihan", "Status","Link","Tanggal Upload"}, 0
        ){
            @Override 
            public boolean isCellEditable(int r,int c){ 
                return false; 
            }
        };
        jTableSertifikat.setModel(tblModel);
        jTableSertifikat.getTableHeader().setReorderingAllowed(false);

        hideColumn(1);

        jTableSertifikat.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) onRowSelected();
        });

        jTableSertifikat.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override 
            public void mouseClicked(java.awt.event.MouseEvent e) {
                if (e.getClickCount() == 2) {
                    int r = jTableSertifikat.rowAtPoint(e.getPoint());
                    if (r >= 0) {
                        String link = String.valueOf(tblModel.getValueAt(r, 4));
                        bukaLink(link);
                    }
                }
            }
        });
    }

    private void onRowSelected() {
        int r = jTableSertifikat.getSelectedRow();
        if (r < 0) {
            selectedId = null;
            linkTerpilih = "";
            jButtonKlikLink.setText("KLIK LINK DISINI");
            jButtonDiterima.setEnabled(false);
            jButtonDitolak.setEnabled(false);
            return;
        }
        selectedId   = (Integer) tblModel.getValueAt(r, 0);
        String status= String.valueOf(tblModel.getValueAt(r, 3));
        linkTerpilih = String.valueOf(tblModel.getValueAt(r, 4));

        jButtonKlikLink.setText(
            linkTerpilih == null || "null".equalsIgnoreCase(linkTerpilih) || linkTerpilih.isBlank()
                ? "KLIK LINK DISINI" : linkTerpilih
        );

        boolean sudahDiterima = "DITERIMA".equalsIgnoreCase(status);
        jButtonDiterima.setEnabled(!sudahDiterima);
        jButtonDitolak.setEnabled(!sudahDiterima);
    }
    
    private void muatData(String q) {
        try {
            tblModel.setRowCount(0);
            var rows = sertifikatSvc.cariUntukVerifikasi(q);

            for (Object[] r : rows) {
                Integer id   = (Integer) r[0];
                Integer nik  = (Integer) r[1];
                String  nama = (String)  r[2];
                Integer idPel = (r[3] instanceof Number n) ? n.intValue() : null;
                String  stt  = (String)  r[4];
                String  lnk  = (String)  r[5];
                String  tgl  = asDateStr(r[6]);
                tblModel.addRow(new Object[]{ id, nik, nama, idPel, stt, lnk, tgl });
            }

            selectedId = null;
            linkTerpilih = "";
            jButtonKlikLink.setText("KLIK LINK DISINI");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Gagal memuat: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
            logger.log(java.util.logging.Level.SEVERE, "Load verifikasi", ex);
        }
    }
    
    private void hubungPencarianLangsung() {
        jTextFieldPencarian.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override 
            public void insertUpdate(DocumentEvent e) { 
                pencarianLangsung(); 
            }
            @Override 
            public void removeUpdate(DocumentEvent e) {
                pencarianLangsung(); 
            }
            @Override 
            public void changedUpdate(DocumentEvent e){
                pencarianLangsung(); 
            }
        });
    }
    private void pencarianLangsung() {
        String q = jTextFieldPencarian.getText().trim();
        muatData(q.isEmpty() ? null : q);
    }
    
    private static String asDateStr(Object o){
        if (o == null) 
            return "-";
        if (o instanceof java.time.LocalDate d)
            return d.toString();
        if (o instanceof java.sql.Date d)     
            return d.toLocalDate().toString();
        return String.valueOf(o);
    }
    private void bukaLink(String link){
        if (link == null || link.isBlank() || "null".equalsIgnoreCase(link)) {
            JOptionPane.showMessageDialog(this, "Tidak ada link untuk dibuka."); 
            return;
        }
        String url = (link.startsWith("http://") || link.startsWith("https://")) ? link : "https://" + link;
        try { java.awt.Desktop.getDesktop().browse(new java.net.URI(url)); }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Gagal membuka: " + url, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void hideColumn(int idx){
        var c = jTableSertifikat.getColumnModel().getColumn(idx);
        c.setMinWidth(0); c.setMaxWidth(0); c.setPreferredWidth(0);
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDiterima;
    private javax.swing.JButton jButtonDitolak;
    private javax.swing.JButton jButtonKembali;
    private javax.swing.JButton jButtonKlikLink;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSertifikat;
    private javax.swing.JTextField jTextFieldPencarian;
    // End of variables declaration//GEN-END:variables
}
